import type { ServicePageContent } from "@/components/sections/ServiceDetailPage";

export const servicePages: Record<string, ServicePageContent> = {
  "branding-and-identity": {
    slug: "branding-and-identity",
    title: "Branding And Identity",
    eyebrow: "Brand System",
    summary: "A complete identity system that makes your brand easier to recognize, trust, and remember across every customer touchpoint.",
    intro: "Brandexa Growth builds brands with a clear point of view: strategy first, visuals second, consistency always. We shape the verbal and visual language your business needs to show up confidently on websites, social media, ads, proposals, and sales material.",
    image: "/wp-content/uploads/2024/11/service-single-img-2.webp",
    highlights: [
      "Clear positioning that separates your offer from similar competitors.",
      "Visual identity systems built for digital, print, and social use.",
      "Brand guidelines your internal team can actually follow.",
      "Messaging that keeps your website, ads, and content aligned.",
    ],
    deliverables: [
      "Brand discovery and positioning",
      "Logo and visual identity direction",
      "Color, typography, and graphic system",
      "Brand voice and messaging framework",
      "Social and campaign identity templates",
      "Practical brand usage guidelines",
    ],
    process: [
      { title: "Discover", text: "We study your audience, competitors, offer, and current brand presence to identify what should be sharpened." },
      { title: "Define", text: "We create the strategic foundation: positioning, promise, voice, message pillars, and visual direction." },
      { title: "Design", text: "We translate the strategy into logo usage, colors, type, graphic elements, and real-world brand applications." },
      { title: "Deploy", text: "We package the system with guidelines and assets so your brand stays consistent after launch." },
    ],
    outcomes: ["Stronger recall", "Clearer positioning", "Consistent presence"],
    faqs: [
      { question: "Do you redesign existing brands?", answer: "Yes. We can refresh an existing identity without losing recognition, or rebuild the brand from the ground up when the current system no longer fits." },
      { question: "Will I receive editable brand files?", answer: "Yes. Final assets are prepared for practical use across web, social, print, and internal brand applications." },
      { question: "Can this include social media templates?", answer: "Yes. We can include reusable post, story, ad, and campaign templates as part of the brand system." },
    ],
  },
  "digital-marketing": {
    slug: "digital-marketing",
    title: "Digital Marketing",
    eyebrow: "Growth Strategy",
    summary: "Performance-focused marketing that connects the right message, channel, audience, and offer to generate measurable growth.",
    intro: "We plan, launch, and optimize digital marketing campaigns across search, social, content, and email. Every campaign is built around a clear goal, tracked with useful metrics, and refined with real performance data.",
    image: "/wp-content/uploads/2024/11/service-single-img-2.webp",
    highlights: [
      "Campaign strategy built around business goals, not vanity metrics.",
      "Audience targeting and messaging mapped to buying intent.",
      "Channel plans across SEO, ads, social, content, and email.",
      "Reporting that explains what happened and what to do next.",
    ],
    deliverables: [
      "Marketing strategy and campaign roadmap",
      "Meta, Google, and social campaign planning",
      "SEO and content growth recommendations",
      "Landing page and conversion suggestions",
      "Audience segmentation and offer messaging",
      "Monthly performance reporting",
    ],
    process: [
      { title: "Audit", text: "We review your current channels, analytics, audience behavior, offers, and conversion paths." },
      { title: "Plan", text: "We define campaign goals, targeting, messaging, creative needs, tracking, and budget priorities." },
      { title: "Launch", text: "We deploy campaigns with clear tracking and creative variations for measurable learning." },
      { title: "Optimize", text: "We monitor results, improve weak points, scale what works, and report the next moves." },
    ],
    outcomes: ["Better leads", "Higher ROI", "Smarter campaigns"],
    faqs: [
      { question: "Which platforms do you manage?", answer: "We can support Google, Meta, Instagram, Facebook, LinkedIn, email, SEO, and content-led campaign activity depending on your goals." },
      { question: "Do you provide reports?", answer: "Yes. Reports focus on performance, insights, and next actions instead of overwhelming dashboards." },
      { question: "Can you work with an existing ad account?", answer: "Yes. We can audit and improve your existing setup or build a cleaner structure from scratch." },
    ],
  },
  "creative-content-production": {
    slug: "creative-content-production",
    title: "Creative Content Production",
    eyebrow: "Creative Engine",
    summary: "High-impact creative assets for campaigns, launches, social media, ads, and brand storytelling.",
    intro: "Creative content production turns strategy into assets your audience can see, understand, and act on. We create visual and written content systems that support campaigns, paid ads, reels, product promotions, and ongoing brand communication.",
    image: "/wp-content/uploads/2024/11/service-single-img-2.webp",
    highlights: [
      "Campaign-ready content designed around one clear message.",
      "Short-form creative formats for social and paid distribution.",
      "Visual consistency that reinforces brand recognition.",
      "Content assets built for repeatable use, not one-off noise.",
    ],
    deliverables: [
      "Campaign creative concepts",
      "Static social and ad creatives",
      "Short-form video direction and scripts",
      "Launch and promotional asset sets",
      "Creative copy and captions",
      "Content template systems",
    ],
    process: [
      { title: "Creative Brief", text: "We define the goal, audience, offer, message, format, and distribution channel for the content." },
      { title: "Concept", text: "We develop creative routes that balance brand style with campaign performance needs." },
      { title: "Produce", text: "We create the visuals, copy, scripts, and content assets needed for launch." },
      { title: "Refine", text: "We review performance signals and improve future creative based on what earns attention and action." },
    ],
    outcomes: ["Stronger creative", "Faster campaigns", "More engagement"],
    faqs: [
      { question: "Do you make content for ads?", answer: "Yes. We create ad-ready visuals and messaging for Meta, Google display, social platforms, and campaign landing experiences." },
      { question: "Can you create content from existing brand assets?", answer: "Yes. We can work within your current brand system or refine it before production if needed." },
      { question: "Do you support video content?", answer: "Yes. We can help with short-form scripts, storyboards, editing direction, and platform-specific creative formats." },
    ],
  },
  "content-creation": {
    slug: "content-creation",
    title: "Content Creation",
    eyebrow: "Content System",
    summary: "Useful, consistent content that helps your audience understand your offer and trust your brand before they buy.",
    intro: "We create content that supports discovery, education, conversion, and retention. From website copy and blog strategy to social posts and email content, we help brands communicate with clarity and consistency.",
    image: "/wp-content/uploads/2024/11/service-single-img-2.webp",
    highlights: [
      "Content pillars aligned with audience questions and business goals.",
      "Copy that explains your offer clearly and persuasively.",
      "Search-aware content planning for long-term discoverability.",
      "Reusable formats that make consistent publishing easier.",
    ],
    deliverables: [
      "Content strategy and topic planning",
      "Website and landing page copy",
      "Blog outlines and article content",
      "Social captions and content calendars",
      "Email campaign copy",
      "Content refresh and optimization",
    ],
    process: [
      { title: "Map", text: "We map your audience questions, decision journey, brand voice, and priority services or products." },
      { title: "Plan", text: "We create content pillars, topic clusters, formats, publishing rhythm, and conversion paths." },
      { title: "Create", text: "We write and structure content that is clear, useful, and aligned with your brand voice." },
      { title: "Improve", text: "We review engagement, search signals, and conversion data to refine the content system over time." },
    ],
    outcomes: ["Clearer messaging", "Consistent publishing", "Better trust"],
    faqs: [
      { question: "Can you write website copy?", answer: "Yes. We create homepage, service page, landing page, and campaign copy that explains the offer and supports conversion." },
      { question: "Do you create content calendars?", answer: "Yes. We can plan weekly or monthly calendars with themes, captions, formats, and creative direction." },
      { question: "Is SEO included?", answer: "Content can be created with search intent, keywords, metadata, and internal linking recommendations where relevant." },
    ],
  },
  "e-commerce-solutions": {
    slug: "e-commerce-solutions",
    title: "E-commerce Solutions",
    eyebrow: "Online Store Growth",
    summary: "Conversion-aware e-commerce experiences that make products easier to discover, trust, and buy.",
    intro: "Brandexa Growth helps e-commerce brands improve the shopping journey from first visit to checkout. We focus on product presentation, collection structure, conversion prompts, campaign landing pages, and retention opportunities.",
    image: "/wp-content/uploads/2024/11/service-single-img-2.webp",
    highlights: [
      "Storefront structure that helps customers find the right products faster.",
      "Product and collection pages designed around trust and purchase intent.",
      "Promotional landing sections for launches, offers, and campaigns.",
      "Conversion improvements across cart, checkout, and follow-up flows.",
    ],
    deliverables: [
      "Storefront experience audit",
      "Product page and collection improvements",
      "E-commerce campaign landing pages",
      "Checkout and conversion recommendations",
      "Email and retention flow planning",
      "Merchandising and offer presentation",
    ],
    process: [
      { title: "Review", text: "We analyze your store journey, product structure, analytics, customer friction, and campaign performance." },
      { title: "Structure", text: "We organize the shopping experience around collections, product intent, trust signals, and conversion paths." },
      { title: "Improve", text: "We create or recommend stronger pages, offer sections, product messaging, and checkout improvements." },
      { title: "Grow", text: "We support launches, promotions, retention, and performance improvements over time." },
    ],
    outcomes: ["More product views", "Higher conversion", "Cleaner shopping"],
    faqs: [
      { question: "Do you build full e-commerce websites?", answer: "Yes. We can support new stores, redesigns, campaign pages, and conversion-focused improvements." },
      { question: "Can you improve an existing store?", answer: "Yes. We can audit your current store and prioritize changes that reduce friction and improve buyer confidence." },
      { question: "Do you help with product copy?", answer: "Yes. Product descriptions, collection copy, offers, and trust-building page content can be included." },
    ],
  },
  "ux-ui-design": {
    slug: "ux-ui-design",
    title: "UX/UI Design",
    eyebrow: "Experience Design",
    summary: "User-focused interface design that makes websites and digital products clearer, easier, and more conversion-ready.",
    intro: "We design digital experiences that balance visual quality with usability. The goal is simple: help users understand where they are, what matters, and what action to take next without friction.",
    image: "/wp-content/uploads/2024/11/service-single-img-2.webp",
    highlights: [
      "User journeys structured around real actions and decisions.",
      "Interface layouts built for clarity, scanning, and conversion.",
      "Responsive design systems for desktop, tablet, and mobile.",
      "Design handoff that helps development stay accurate and efficient.",
    ],
    deliverables: [
      "UX audit and journey mapping",
      "Wireframes and page structure",
      "High-fidelity UI design",
      "Responsive design layouts",
      "Component and design system direction",
      "Developer-ready design handoff",
    ],
    process: [
      { title: "Understand", text: "We clarify the audience, goals, user journeys, conversion needs, and current friction points." },
      { title: "Structure", text: "We plan the information architecture, page flow, wireframes, and priority content hierarchy." },
      { title: "Design", text: "We create polished interface designs that are responsive, accessible, and brand-aligned." },
      { title: "Hand Off", text: "We prepare clear design assets and notes so implementation is smoother and more accurate." },
    ],
    outcomes: ["Clearer journeys", "Better usability", "Higher conversions"],
    faqs: [
      { question: "Can you redesign an existing website?", answer: "Yes. We can audit the current experience and redesign the interface while keeping useful existing content and brand equity." },
      { question: "Do you provide mobile designs?", answer: "Yes. Responsive desktop, tablet, and mobile layouts can be included depending on the project scope." },
      { question: "Can developers use your designs?", answer: "Yes. We prepare designs and notes for practical implementation, including components, states, spacing, and responsive behavior." },
    ],
  },
  "social-media-marketing": {
    slug: "social-media-marketing",
    title: "Social Media Marketing",
    eyebrow: "Organic Social Growth",
    summary: "Consistent social media strategy and content that helps your brand stay visible, useful, and memorable.",
    intro: "Brandexa Growth manages social media with a clear system: audience insight, content pillars, creative direction, posting rhythm, and performance review. We help brands show up consistently without sounding random or repetitive.",
    image: "/wp-content/uploads/2024/11/service-single-img-2.webp",
    highlights: [
      "Content pillars built around your audience, offer, and brand voice.",
      "Platform-specific content for Instagram, Facebook, LinkedIn, and more.",
      "Consistent posting systems that keep your brand active and recognizable.",
      "Monthly insights that reveal what content earns attention and action.",
    ],
    deliverables: [
      "Social media strategy",
      "Monthly content calendar",
      "Caption and creative direction",
      "Profile optimization",
      "Community engagement guidance",
      "Performance reporting",
    ],
    process: [
      { title: "Audit", text: "We review your profiles, content, competitors, audience behavior, and current engagement signals." },
      { title: "Plan", text: "We create content pillars, post formats, publishing rhythm, and campaign themes." },
      { title: "Create", text: "We prepare content ideas, captions, visual direction, and platform-ready assets." },
      { title: "Improve", text: "We review engagement patterns and adjust the content plan for stronger consistency and relevance." },
    ],
    outcomes: ["Consistent presence", "More engagement", "Stronger brand trust"],
    faqs: [
      { question: "Which platforms do you support?", answer: "We can support Instagram, Facebook, LinkedIn, and other relevant platforms depending on your audience and goals." },
      { question: "Do you create the captions and content ideas?", answer: "Yes. Captions, content themes, post ideas, and creative direction can be included in the monthly plan." },
      { question: "Is this different from social media ads?", answer: "Yes. Social media marketing focuses on organic content and presence, while social media ads are paid campaigns for reach, traffic, leads, or sales." },
    ],
  },
  "google-ads": {
    slug: "google-ads",
    title: "Google Ads",
    eyebrow: "Search And Demand Capture",
    summary: "Google Ads campaigns built to capture high-intent searches and turn them into qualified leads, calls, and sales.",
    intro: "We structure Google Ads around search intent, landing page relevance, clean tracking, and practical budget control. The goal is to put your offer in front of people already looking for what you provide.",
    image: "/wp-content/uploads/2024/11/service-single-img-2.webp",
    highlights: [
      "Keyword strategy organized around intent and business value.",
      "Campaign structures that separate brand, service, location, and conversion goals.",
      "Ad copy and extensions written for clarity, relevance, and action.",
      "Tracking and reporting that make spend, leads, and results easier to understand.",
    ],
    deliverables: [
      "Google Ads account audit",
      "Keyword and competitor research",
      "Search campaign setup",
      "Ad copy and extensions",
      "Conversion tracking guidance",
      "Optimization and reporting",
    ],
    process: [
      { title: "Research", text: "We identify high-intent keywords, search behavior, competitors, and budget opportunities." },
      { title: "Build", text: "We structure campaigns, ad groups, keywords, ads, extensions, and conversion goals." },
      { title: "Launch", text: "We launch with clear tracking and review early data to catch wasted spend quickly." },
      { title: "Optimize", text: "We refine keywords, bids, copy, landing pages, and budgets based on performance." },
    ],
    outcomes: ["More qualified leads", "Cleaner ad spend", "Higher intent traffic"],
    faqs: [
      { question: "Do you manage existing Google Ads accounts?", answer: "Yes. We can audit, clean up, restructure, and optimize existing accounts." },
      { question: "Can you set up conversion tracking?", answer: "We can guide or implement tracking for calls, forms, purchases, or other key conversion actions depending on your setup." },
      { question: "How soon can campaigns launch?", answer: "Simple campaigns can usually be prepared quickly after access, goals, keywords, landing pages, and tracking are confirmed." },
    ],
  },
  "social-media-ads": {
    slug: "social-media-ads",
    title: "Social Media Ads",
    eyebrow: "Paid Social Campaigns",
    summary: "Paid social campaigns that pair strong creative with precise targeting, testing, and conversion-focused optimization.",
    intro: "We build social media ad campaigns for awareness, engagement, leads, traffic, and sales. Each campaign is structured around the audience, offer, creative angle, landing experience, and performance data.",
    image: "/wp-content/uploads/2024/11/service-single-img-2.webp",
    highlights: [
      "Campaign strategy for Meta, Instagram, Facebook, LinkedIn, and other platforms.",
      "Audience structures built around intent, interest, retargeting, and lookalike opportunities.",
      "Creative testing plans that reveal which messages and visuals perform best.",
      "Optimization based on cost, conversion quality, and campaign objective.",
    ],
    deliverables: [
      "Paid social campaign strategy",
      "Audience and funnel planning",
      "Ad creative direction",
      "Campaign setup and launch",
      "Retargeting recommendations",
      "Performance optimization",
    ],
    process: [
      { title: "Define", text: "We clarify the campaign goal, offer, audience, budget, conversion action, and funnel stage." },
      { title: "Create", text: "We prepare ad angles, visuals, copy, and testing variations for the selected platform." },
      { title: "Launch", text: "We configure campaigns, audiences, placements, budgets, and tracking before launch." },
      { title: "Scale", text: "We monitor results, reduce waste, improve creative, and scale what proves efficient." },
    ],
    outcomes: ["Lower wasted spend", "Better creative tests", "More campaign clarity"],
    faqs: [
      { question: "Which ad platforms do you support?", answer: "We can support Meta Ads, Instagram/Facebook campaigns, LinkedIn Ads, and other paid social platforms where relevant." },
      { question: "Do you create ad creatives?", answer: "Yes. Creative direction, copy, static ads, and short-form ad concepts can be included." },
      { question: "Can you run retargeting campaigns?", answer: "Yes. We can structure retargeting campaigns for website visitors, engaged users, leads, or customer audiences when tracking is available." },
    ],
  },
  "video-editing": {
    slug: "video-editing",
    title: "Video Editing",
    eyebrow: "Short-Form And Brand Video",
    summary: "Polished video edits for social media, ads, launches, testimonials, reels, and brand storytelling.",
    intro: "We edit videos so they feel clear, paced, branded, and platform-ready. From short-form social clips to promotional edits, we shape raw footage into content that holds attention and supports your message.",
    image: "/wp-content/uploads/2024/11/service-single-img-2.webp",
    highlights: [
      "Short-form edits designed for Reels, Shorts, TikTok, and paid ads.",
      "Clean pacing, hooks, captions, music, transitions, and brand styling.",
      "Repurposing long-form footage into multiple smaller clips.",
      "Platform-ready exports with the correct formats and aspect ratios.",
    ],
    deliverables: [
      "Short-form video edits",
      "Ad video edits",
      "Captions and subtitles",
      "Motion graphics and branded overlays",
      "Long-form to short-form repurposing",
      "Platform-ready exports",
    ],
    process: [
      { title: "Review", text: "We review your footage, goal, brand style, platform, and desired message." },
      { title: "Structure", text: "We shape the hook, sequence, pacing, captions, and call to action." },
      { title: "Edit", text: "We assemble the video with music, transitions, graphics, subtitles, and brand elements." },
      { title: "Export", text: "We prepare final versions for the required formats, aspect ratios, and platforms." },
    ],
    outcomes: ["Sharper videos", "More watch time", "Reusable clips"],
    faqs: [
      { question: "Can you edit reels and shorts?", answer: "Yes. We edit short-form videos for Instagram Reels, YouTube Shorts, TikTok, Facebook, and paid ad placements." },
      { question: "Do you add captions?", answer: "Yes. Captions, subtitles, hooks, overlays, and branded text treatments can be included." },
      { question: "Can you repurpose long videos?", answer: "Yes. We can turn webinars, interviews, podcasts, or long clips into multiple short-form assets." },
    ],
  },
};
