import { CmsProject } from "@/types/cms";

export const OUR_WORK_CMS_PROJECTS: CmsProject[] = [
  {
    id: "scoogie-events",
    title: "Scoogie Events",
    clientName: "Scoogie Events",
    slug: "scoogie-events",
    categories: ["Branding & Identity", "Campaign Creative", "Local Business"],
    heroImage: "/work-samples/scoogie-events.webp",
    galleryImages: ["/work-samples/scoogie-events.webp"],
    challenge: "Scoogie Events faced visual fragmentation across print flyers and social media campaigns which confused participants. Event registration landing pages suffered from high drop-off rates due to complex navigation structures and lack of mobile optimization.",
    solution: "Developed a structured branding and identity system with distinct guidelines, typography, modular social templates for Instagram/Facebook, and a frictionless registration conversion funnel.",
    metrics: [
      { id: "m1", label: "Faster Campaign Rollout", value: "3.2x" },
      { id: "m2", label: "Lift in Social Engagement", value: "+42%" },
      { id: "m3", label: "Reusable Templates", value: "18" },
    ],
    testimonial: {
      quote: "The new brand system made our campaigns feel more consistent and easier to launch. It completely refreshed how we communicate with our community and sponsors alike.",
      clientName: "Event Director",
      clientRole: "Scoogie Events",
    },
    isFeatured: true,
    orderIndex: 0,
    status: "published",
    createdAt: "2024-11-01T00:00:00.000Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "wallhogs",
    title: "Wallhogs",
    clientName: "Wallhogs",
    slug: "wallhogs",
    categories: ["Website", "Social Media Management", "E-Commerce"],
    heroImage: "/work-samples/wallhogs.webp",
    galleryImages: ["/work-samples/wallhogs.webp"],
    challenge: "Stagnant organic engagement and low visibility across Facebook and Instagram. Custom wall decals and murals required visual context to demonstrate scale and quality, which was not being conveyed in their previous social posts.",
    solution: "Visual storytelling strategy featuring UGC, customer home tours, step-by-step installation guides, active channel moderation, and direct shoppable configurator conversion paths.",
    metrics: [
      { id: "m1", label: "Facebook Total Views", value: "56.9K" },
      { id: "m2", label: "Facebook Organic Reach", value: "31.8K" },
      { id: "m3", label: "Website Session Growth", value: "+122.9%" },
    ],
    testimonial: {
      quote: "The creativity and communication have been outstanding and we finally see real growth across all our key marketing metrics.",
      clientName: "Paul Conklin",
      clientRole: "Founder, Wallhogs",
    },
    isFeatured: true,
    orderIndex: 1,
    status: "published",
    createdAt: "2024-11-01T00:00:00.000Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "mission-hills",
    title: "Mission Hills",
    clientName: "Mission Hills Country Club",
    slug: "mission-hills",
    categories: ["Campaign Strategy", "Social Media Ads", "Sports & Leisure"],
    heroImage: "/work-samples/mission-hills.webp",
    galleryImages: ["/work-samples/mission-hills.webp"],
    challenge: "Target market was highly fragmented across casual golfers, tournament organizers, and family membership prospects, leading to high ad budget waste and rising acquisition costs.",
    solution: "Developed a unified seasonal marketing calendar matching high-intent membership periods and executed precision-targeted Meta advertising campaigns.",
    metrics: [
      { id: "m1", label: "Campaign Reach Lift", value: "+48%" },
      { id: "m2", label: "Landing Page Visits", value: "2.1x" },
      { id: "m3", label: "Lower Cost Per Inquiry", value: "-34%" },
    ],
    testimonial: {
      quote: "The campaign structure gave our team more clarity and better weekly momentum. It lowered our acquisition costs dramatically and simplified our message.",
      clientName: "Marketing Director",
      clientRole: "Mission Hills",
    },
    isFeatured: true,
    orderIndex: 2,
    status: "published",
    createdAt: "2024-11-01T00:00:00.000Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "future-leaders",
    title: "Future Leaders",
    clientName: "Future Leaders Foundation",
    slug: "future-leaders",
    categories: ["Content Creation", "Short Video Marketing", "Education"],
    heroImage: "/work-samples/future-leaders.webp",
    galleryImages: ["/work-samples/future-leaders.webp"],
    challenge: "Program updates were useful but lacked a repeatable, structured framework that could be easily consumed by parents on social channels.",
    solution: "Established distinct content buckets focusing on Student Spotlights, Educational Insights, and Program Achievements alongside short-form TikTok & Reels production.",
    metrics: [
      { id: "m1", label: "Reusable Content Formats", value: "24" },
      { id: "m2", label: "Increase in Engagement", value: "+39%" },
      { id: "m3", label: "Publishing Consistency", value: "3x" },
    ],
    testimonial: {
      quote: "The content finally feels organized and easy for our team to keep using. It has significantly improved how families interact with our school.",
      clientName: "Admissions Director",
      clientRole: "Future Leaders",
    },
    isFeatured: true,
    orderIndex: 3,
    status: "published",
    createdAt: "2024-11-01T00:00:00.000Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "bright-dental",
    title: "Bright Dental",
    clientName: "Bright Dental Clinic",
    slug: "bright-dental",
    categories: ["SEO & Analytics", "Local SEO", "Healthcare"],
    heroImage: "/work-samples/bright-dental.webp",
    galleryImages: ["/work-samples/bright-dental.webp"],
    challenge: "Key service pages were not appearing on the first page of search results for localized dental queries, and appointment conversion was low due to friction on mobile.",
    solution: "On-page search optimization, local Google Business Profile cleanup, review acquisition workflows, and a streamlined mobile appointment booking flow.",
    metrics: [
      { id: "m1", label: "Local Impressions Lift", value: "+64%" },
      { id: "m2", label: "Service Page Visits", value: "+27%" },
      { id: "m3", label: "Appointment Actions", value: "+19%" },
    ],
    testimonial: {
      quote: "Search leads became easier to understand, our pages started working harder, and our appointment calendars have never been fuller.",
      clientName: "Dr. Rachel Adams",
      clientRole: "Lead Practitioner, Bright Dental",
    },
    isFeatured: true,
    orderIndex: 4,
    status: "published",
    createdAt: "2024-11-01T00:00:00.000Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "urban-threads",
    title: "Urban Threads",
    clientName: "Urban Threads Apparel",
    slug: "urban-threads",
    categories: ["E-Commerce", "Storefront Design", "Apparel / Fashion"],
    heroImage: "/work-samples/urban-threads.webp",
    galleryImages: ["/work-samples/urban-threads.webp"],
    challenge: "Mobile shopping cart experience suffered from high abandonment rates due to excessive checkout steps and unstructured product browsing.",
    solution: "Mobile-first storefront overhaul, 1-page checkout integration, dynamic collection filters, and lifestyle visual merchandising.",
    metrics: [
      { id: "m1", label: "Product Views Increase", value: "+31%" },
      { id: "m2", label: "Higher Add-to-Cart Actions", value: "+22%" },
      { id: "m3", label: "Returning Visits Lift", value: "+16%" },
    ],
    testimonial: {
      quote: "The storefront feels cleaner, faster to browse, and easier to promote. Our customer support team has seen a huge drop in checkout questions.",
      clientName: "Marcus Vance",
      clientRole: "Founder, Urban Threads",
    },
    isFeatured: true,
    orderIndex: 5,
    status: "published",
    createdAt: "2024-11-01T00:00:00.000Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "clearon-bleach-tablets",
    title: "Clearon Bleach Tablets",
    clientName: "Clearon Bleach",
    slug: "clearon-bleach-tablets",
    categories: ["Social Media Marketing", "E-Commerce", "Consumer Products"],
    heroImage: "/work-samples/clearon.webp",
    galleryImages: ["/work-samples/clearon.webp"],
    challenge: "Establishing brand awareness in 700+ Walmart locations and engaging younger demographics and college students who traditionally do not purchase bleach products.",
    solution: "Dorm hacks and laundry tips social media campaign, active real-time Twitter/X keyword listening, and tailored college student giveaways.",
    metrics: [
      { id: "m1", label: "Follower Increase", value: "+430%" },
      { id: "m2", label: "Revenue Increase", value: "+112%" },
      { id: "m3", label: "Total Impressions", value: "1.0M+" },
    ],
    testimonial: {
      quote: "I knew digital marketing would help with social media, but still, I just didn’t think people would talk and tweet this much about bleach! The response was incredible.",
      clientName: "Marketing Director",
      clientRole: "Clearon Bleach Tablets",
    },
    isFeatured: false,
    orderIndex: 6,
    status: "published",
    createdAt: "2024-11-01T00:00:00.000Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "ray-of-hope",
    title: "Ray of Hope Christian Church",
    clientName: "Ray of Hope",
    slug: "ray-of-hope",
    categories: ["Social Media Marketing", "Nonprofit", "Community"],
    heroImage: "/work-samples/ray-of-hope.webp",
    galleryImages: ["/work-samples/ray-of-hope.webp"],
    challenge: "Traditional physical outreach was failing to connect with new residents moving to the local area, requiring a modern digital outreach system.",
    solution: "Localized Twitter engagement, Sunday worship live stream promotion countdowns, and inspirational quote cards.",
    metrics: [
      { id: "m1", label: "Total Audience", value: "16,078" },
      { id: "m2", label: "Physical Visitation Lift", value: "+28%" },
      { id: "m3", label: "Website Traffic", value: "+123%" },
    ],
    testimonial: {
      quote: "We attracted thousands of people and increased visitation in less than a couple of months through targeted digital community engagement.",
      clientName: "Church Administrator",
      clientRole: "Ray of Hope Christian Church",
    },
    isFeatured: false,
    orderIndex: 7,
    status: "published",
    createdAt: "2024-11-01T00:00:00.000Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cafe-alibaba",
    title: "Cafe Alibaba",
    clientName: "Café Alibaba",
    slug: "cafe-alibaba",
    categories: ["Social Media Marketing", "Restaurant", "Food & Beverage"],
    heroImage: "/work-samples/cafe-alibaba.webp",
    galleryImages: ["/work-samples/cafe-alibaba.webp"],
    challenge: "Short campaign window before the university semester began to build complete brand awareness among incoming students in a crowded dining district.",
    solution: "Targeted student Happy Hour specials, instant social follow discounts, and local keyword listening around campus food searches.",
    metrics: [
      { id: "m1", label: "Followers Gained (<2 Mo)", value: "1,298" },
      { id: "m2", label: "Twitter Community", value: "1,000+" },
      { id: "m3", label: "Student Foot Traffic", value: "+180%" },
    ],
    testimonial: {
      quote: "Within the first few weeks, Café Alibaba received extensive traffic from the university audience asking about our specials.",
      clientName: "Cafe Owner",
      clientRole: "Café Alibaba",
    },
    isFeatured: false,
    orderIndex: 8,
    status: "published",
    createdAt: "2024-11-01T00:00:00.000Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "mortgage-markets-cuso",
    title: "Mortgage Markets CUSO",
    clientName: "Mortgage Markets CUSO",
    slug: "mortgage-markets-cuso",
    categories: ["Social Media Ads", "Finance", "B2B"],
    heroImage: "/work-samples/mortgage-markets-cuso.webp",
    galleryImages: ["/work-samples/mortgage-markets-cuso.webp"],
    challenge: "Frustrated by previous agencies using generic stock templates that did not match the sophistication of B2B credit union partnerships and first-time homebuyer education.",
    solution: "Bespoke custom on-brand graphics, mortgage planning educational carousels, and targeted Meta/LinkedIn campaigns.",
    metrics: [
      { id: "m1", label: "Instagram Views", value: "+90.7%" },
      { id: "m2", label: "Instagram Reach", value: "+248%" },
      { id: "m3", label: "Facebook Reach Lift", value: "+41.2%" },
    ],
    testimonial: {
      quote: "In my world, marketing and social media awareness are critical. Brandexa has helped us reach the next level with precision.",
      clientName: "Michael Ferraro",
      clientRole: "President, Mortgage Markets CUSO",
    },
    isFeatured: false,
    orderIndex: 9,
    status: "published",
    createdAt: "2024-11-01T00:00:00.000Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "arctic-collagen",
    title: "Arctic Collagen",
    clientName: "ArcticCollagen™",
    slug: "arctic-collagen",
    categories: ["Social Media Marketing", "Wellness", "E-Commerce"],
    heroImage: "/work-samples/arctic-collagen.webp",
    galleryImages: ["/work-samples/arctic-collagen.webp"],
    challenge: "Zero existing footprint in a crowded wellness supplement space dominated by bovine-derived collagen products.",
    solution: "Influencer collaborations, relatable Facetime-style routine videos, and high-converting email acquisition discount magnets.",
    metrics: [
      { id: "m1", label: "Facebook Reach Lift", value: "+7.3M%" },
      { id: "m2", label: "Instagram Engagement", value: "+100%" },
      { id: "m3", label: "Video Views", value: "104.4K" },
    ],
    testimonial: {
      quote: "Entering a highly competitive market from scratch required a team that understood how to build trust quickly.",
      clientName: "Lennart & Jasmien Winqvist",
      clientRole: "Founders, Arctic Collagen",
    },
    isFeatured: false,
    orderIndex: 10,
    status: "published",
    createdAt: "2024-11-01T00:00:00.000Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "vital-vibe-fitness",
    title: "Vital Vibe Health N Fitness",
    clientName: "Vital Vibe Fitness",
    slug: "vital-vibe-fitness",
    categories: ["Social Media Management", "Fitness", "Health & Wellness"],
    heroImage: "/work-samples/vital-vibe-fitness.webp",
    galleryImages: ["/work-samples/vital-vibe-fitness.webp"],
    challenge: "Solo founder lacked the time to manage daily social content while designing new fitness apparel products.",
    solution: "Motivational brand voice playbook, launch support content for the fitness apparel line, and video testimonial series.",
    metrics: [
      { id: "m1", label: "Increase In Reach", value: "+228.7K%" },
      { id: "m2", label: "Video Views", value: "35K" },
      { id: "m3", label: "Top Post Reach", value: "5.6K" },
    ],
    testimonial: {
      quote: "Working with Brandexa has been a game-changer. As a solo founder with big goals, I needed a team that could handle the marketing side—and they delivered.",
      clientName: "Ellijah Gardaya",
      clientRole: "Founder, Vital Vibe Fitness",
    },
    isFeatured: false,
    orderIndex: 11,
    status: "published",
    createdAt: "2024-11-01T00:00:00.000Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "wrecked-angles",
    title: "Wrecked Angles",
    clientName: "Wrecked Angles",
    slug: "wrecked-angles",
    categories: ["Social Media Ads", "Automotive", "Entertainment"],
    heroImage: "/work-samples/wrecked-angles.webp",
    galleryImages: ["/work-samples/wrecked-angles.webp"],
    challenge: "Struggled to expand visibility beyond existing followers organically due to competitors posting viral copied memes.",
    solution: "Targeted paid page-growth ad campaigns, lookalike audiences of engaged fans, and hyper-optimized cost-per-engagement bidding.",
    metrics: [
      { id: "m1", label: "New Followers Gained", value: "101.4K" },
      { id: "m2", label: "Increase in Reach", value: "+2,700%" },
      { id: "m3", label: "Total Views", value: "11M+" },
    ],
    testimonial: {
      quote: "I’ve gotten results FAR exceeding my goals! Couldn’t be more pleased with the growth trajectory.",
      clientName: "John Kanthak",
      clientRole: "Creator, Wrecked Angles",
    },
    isFeatured: false,
    orderIndex: 12,
    status: "published",
    createdAt: "2024-11-01T00:00:00.000Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "axiom-structures",
    title: "Axiom Structures",
    clientName: "Axiom Structures",
    slug: "axiom-structures",
    categories: ["Social Media Management", "B2B", "Construction"],
    heroImage: "/work-samples/axiom-structures.webp",
    galleryImages: ["/work-samples/axiom-structures.webp"],
    challenge: "Strong offline engineering reputation but near zero online presence with only 100 followers on social media.",
    solution: "Branded visual themes highlighting blueprint details, completed project photography, and structural inspection guides.",
    metrics: [
      { id: "m1", label: "Facebook Growth", value: "+353%" },
      { id: "m2", label: "Instagram Growth", value: "+165%" },
      { id: "m3", label: "Monthly Interactions", value: "18x" },
    ],
    testimonial: {
      quote: "Brandexa keeps in touch with me each month, their product is fantastic, and our reach has grown exponentially in just a few months!",
      clientName: "Lead Engineer",
      clientRole: "Axiom Structures",
    },
    isFeatured: false,
    orderIndex: 13,
    status: "published",
    createdAt: "2024-11-01T00:00:00.000Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "daryl-d-black",
    title: "Daryl D Black Coaching",
    clientName: "Daryl D. Black",
    slug: "daryl-d-black",
    categories: ["Social Media Ads", "Personal Brand", "Coaching"],
    heroImage: "/work-samples/daryl-d-black.webp",
    galleryImages: ["/work-samples/daryl-d-black.webp"],
    challenge: "Attracting high-paying executive consulting clients on a conservative daily budget.",
    solution: "High-converting Facebook Lead Form campaigns with custom qualification questions and stress-under-pressure hook angles.",
    metrics: [
      { id: "m1", label: "Executive Leads Gained", value: "202" },
      { id: "m2", label: "Monthly Lead Growth", value: "+1,000%" },
      { id: "m3", label: "Daily Ad Budget", value: "$20/day" },
    ],
    testimonial: {
      quote: "Communicates very well, follows through on asks, and always produces. I’m impressed by the team’s agility and capability.",
      clientName: "Daryl D. Black",
      clientRole: "Executive Leadership Coach",
    },
    isFeatured: false,
    orderIndex: 14,
    status: "published",
    createdAt: "2024-11-01T00:00:00.000Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "spray-daze-tan",
    title: "Spray Daze Tan",
    clientName: "Spray Daze Tan",
    slug: "spray-daze-tan",
    categories: ["Social Media Ads", "Beauty", "Local Business"],
    heroImage: "/work-samples/spray-daze.webp",
    galleryImages: ["/work-samples/spray-daze.webp"],
    challenge: "High seasonal booking volatility and generic stock imagery failing to set them apart from discount franchise competitors.",
    solution: "Gender-specific ad groups, hook-based copy testing ('Feeling Pasty?'), and retargeting 'New Client' introductory offers.",
    metrics: [
      { id: "m1", label: "Appointments Booked", value: "172" },
      { id: "m2", label: "Cost Per Lead", value: "$4.23" },
      { id: "m3", label: "Click-Through Rate", value: "+45%" },
    ],
    testimonial: {
      quote: "We’re already at 22 new clients who booked in the first 7 days since we started. Whatever marketing you're doing is working great!",
      clientName: "Brittany Duckworth",
      clientRole: "Founder, Spray Daze Tan",
    },
    isFeatured: false,
    orderIndex: 15,
    status: "published",
    createdAt: "2024-11-01T00:00:00.000Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "dynamic-e-commerce-platform",
    title: "Dynamic E-Commerce Platform",
    clientName: "Aura Apparel",
    slug: "dynamic-e-commerce-platform",
    categories: ["Branding & Identity", "Digital Marketing", "Web Design"],
    heroImage: "/wp-content/uploads/2024/11/project-1-2.webp",
    galleryImages: ["/wp-content/uploads/2024/11/project-1-2.webp", "/wp-content/uploads/2024/11/gallery-1-2.webp", "/wp-content/uploads/2024/11/gallery-2-2.webp"],
    challenge: "Aura Apparel struggled with high cart abandonment and slow mobile page speeds that limited paid campaign ROAS.",
    solution: "Brandexa re-engineered the storefront on a modern Next.js headless architecture with instantaneous 1-click checkout and customized bundling.",
    metrics: [
      { id: "m1", label: "Conversion Rate Increase", value: "+184%" },
      { id: "m2", label: "Average Order Value", value: "+38%" },
      { id: "m3", label: "Page Load Speed", value: "0.4s" },
    ],
    testimonial: {
      quote: "Brandexa transformed our entire online revenue engine. The performance gains were felt in our balance sheet within 30 days.",
      clientName: "David Vance",
      clientRole: "CEO, Aura Apparel",
    },
    isFeatured: true,
    orderIndex: 16,
    status: "published",
    createdAt: "2024-11-01T00:00:00.000Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "innovative-identity-design",
    title: "Innovative Identity Design",
    clientName: "Synthex Bio",
    slug: "innovative-identity-design",
    categories: ["Digital Marketing", "Web Design"],
    heroImage: "/wp-content/uploads/2024/11/project-2-3.webp",
    galleryImages: ["/wp-content/uploads/2024/11/project-2-3.webp", "/wp-content/uploads/2024/11/gallery-3-2.webp"],
    challenge: "Synthex Bio lacked visual differentiation in a crowded biotech market, hindering their Series B investor and enterprise client outreach.",
    solution: "We engineered an ultra-modern futuristic brand identity, interactive 3D website, and comprehensive corporate asset library.",
    metrics: [
      { id: "m1", label: "Investor Inquiries", value: "+260%" },
      { id: "m2", label: "Time on Site", value: "+3.8 min" },
    ],
    testimonial: {
      quote: "The new identity gave our company instant credibility with institutional investors and enterprise clients alike.",
      clientName: "Elena Rostova",
      clientRole: "Managing Director, Synthex Bio",
    },
    isFeatured: true,
    orderIndex: 17,
    status: "published",
    createdAt: "2024-11-01T00:00:00.000Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "dynamic-digital-campaign",
    title: "Dynamic Digital Campaign",
    clientName: "Nova Energy",
    slug: "dynamic-digital-campaign",
    categories: ["Branding & Identity", "SEO & Analytics"],
    heroImage: "/wp-content/uploads/2024/11/project-3-2.webp",
    galleryImages: ["/wp-content/uploads/2024/11/project-3-2.webp"],
    challenge: "Nova Energy needed rapid customer acquisition across key European metros with strict cost-per-acquisition (CPA) targets.",
    solution: "Brandexa deployed targeted search and dynamic social creative funnels with hyper-localized landing pages.",
    metrics: [
      { id: "m1", label: "CPA Reduction", value: "-44%" },
      { id: "m2", label: "Monthly Qualified Leads", value: "3,800+" },
    ],
    testimonial: {
      quote: "The lead quality surpassed our expectations and enabled our sales team to scale aggressively without burning budget.",
      clientName: "Henrik Lindqvist",
      clientRole: "VP Marketing, Nova Energy",
    },
    isFeatured: true,
    orderIndex: 18,
    status: "published",
    createdAt: "2024-11-01T00:00:00.000Z",
    updatedAt: new Date().toISOString(),
  },
];
